# Generated by Django 3.1.6 on 2021-03-25 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('emailid', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('fname', models.CharField(default='none', max_length=100)),
                ('pwd', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'userdetails',
            },
        ),
        migrations.CreateModel(
            name='savetodb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axial', models.BinaryField(blank=True)),
                ('cor', models.BinaryField(blank=True)),
                ('sag', models.BinaryField(blank=True)),
                ('emailid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signin.user')),
            ],
        ),
    ]
