# Generated by Django 3.1.6 on 2021-04-01 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savetodb',
            name='aclstatus',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='savetodb',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savetodb',
            name='emailid',
            field=models.EmailField(max_length=254),
        ),
    ]
